#This is manifest file to define a Kubernetes ReplicaSet configuration in YAML format.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: docker-practice/apache-docker-web
          ports:
            - containerPort: 80